In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pprint
import pyspark
import pyspark.sql.functions as F

from pyspark.sql.functions import col
from pyspark.sql.types import StringType, IntegerType, FloatType, DateType

os.environ["PYSPARK_PYTHON"] = "python"
os.environ["PYSPARK_DRIVER_PYTHON"] = "python"

import utils.data_processing_bronze_table
import utils.data_processing_silver_loan
import utils.data_processing_silver_attributes
import utils.data_processing_silver_financials
import utils.data_processing_silver_clickstream
import utils.data_processing_gold_table

## Setup config

In [3]:
# set path for Hadoop
os.environ["HADOOP_HOME"] = "C:\\hadoop"
os.environ["PATH"] = os.environ["PATH"] + ";C:\\hadoop\\bin"

### set up pyspark session

In [4]:
# Initialize SparkSession
spark = pyspark.sql.SparkSession.builder \
    .appName("dev") \
    .master("local[*]") \
    .getOrCreate()

# Set log level to ERROR to hide warnings
spark.sparkContext.setLogLevel("ERROR")

### set up config

In [5]:
# set up config
snapshot_date_str = "2023-01-01"

start_date_str = "2023-01-01"
end_date_str = "2025-11-01"

In [6]:
# generate list of dates to process
def generate_first_of_month_dates(start_date_str, end_date_str):
    # Convert the date strings to datetime objects
    start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
    end_date = datetime.strptime(end_date_str, "%Y-%m-%d")
    
    # List to store the first of month dates
    first_of_month_dates = []

    # Start from the first of the month of the start_date
    current_date = datetime(start_date.year, start_date.month, 1)

    while current_date <= end_date:
        # Append the date in yyyy-mm-dd format
        first_of_month_dates.append(current_date.strftime("%Y-%m-%d"))
        
        # Move to the first of the next month
        if current_date.month == 12:
            current_date = datetime(current_date.year + 1, 1, 1)
        else:
            current_date = datetime(current_date.year, current_date.month + 1, 1)

    return first_of_month_dates

dates_str_lst = generate_first_of_month_dates(start_date_str, end_date_str)
dates_str_lst

['2023-01-01',
 '2023-02-01',
 '2023-03-01',
 '2023-04-01',
 '2023-05-01',
 '2023-06-01',
 '2023-07-01',
 '2023-08-01',
 '2023-09-01',
 '2023-10-01',
 '2023-11-01',
 '2023-12-01',
 '2024-01-01',
 '2024-02-01',
 '2024-03-01',
 '2024-04-01',
 '2024-05-01',
 '2024-06-01',
 '2024-07-01',
 '2024-08-01',
 '2024-09-01',
 '2024-10-01',
 '2024-11-01',
 '2024-12-01',
 '2025-01-01',
 '2025-02-01',
 '2025-03-01',
 '2025-04-01',
 '2025-05-01',
 '2025-06-01',
 '2025-07-01',
 '2025-08-01',
 '2025-09-01',
 '2025-10-01',
 '2025-11-01']

## Build Bronze Table

In [7]:
# create bronze datalake
bronze_loan_directory = "datamart/bronze/loan/"
bronze_clickstream_directory = "datamart/bronze/clickstream/"
bronze_attributes_directory = "datamart/bronze/attributes/"
bronze_financials_directory = "datamart/bronze/financials/"

for d in [bronze_loan_directory, bronze_clickstream_directory, 
          bronze_attributes_directory, bronze_financials_directory]:
    if not os.path.exists(d):
        os.makedirs(d)

In [8]:
# run bronze backfill for all tables
bronze_tables = [
    ("lms_loan_daily", bronze_loan_directory),
    ("feature_clickstream", bronze_clickstream_directory),
    ("features_attributes", bronze_attributes_directory),
    ("features_financials", bronze_financials_directory),
]

for data_file_name, directory in bronze_tables:
    print(f"\n=== Processing {data_file_name} ===")
    for date_str in dates_str_lst:
        utils.data_processing_bronze_table.process_bronze_table(
            date_str, directory, spark, data_file_name
        )

=== Processing lms_loan_daily ===
2023-01-01 | lms_loan_daily | row count: 530
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_01_01.csv
2023-02-01 | lms_loan_daily | row count: 1031
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_02_01.csv
2023-03-01 | lms_loan_daily | row count: 1537
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_03_01.csv
2023-04-01 | lms_loan_daily | row count: 2047
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_04_01.csv
2023-05-01 | lms_loan_daily | row count: 2568
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_05_01.csv
2023-06-01 | lms_loan_daily | row count: 3085
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_06_01.csv
2023-07-01 | lms_loan_daily | row count: 3556
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_07_01.csv
2023-08-01 | lms_loan_daily | row count: 4037
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_08_01.csv
2023-09-01 | lms_loan_daily | row count: 4491
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_09_01.csv
2023-10-01 | lms_loan_daily | row count: 4978
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_10_01.csv
2023-11-01 | lms_loan_daily | row count: 5469
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_11_01.csv
2023-12-01 | lms_loan_daily | row count: 5428
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2023_12_01.csv
2024-01-01 | lms_loan_daily | row count: 5412
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_01_01.csv
2024-02-01 | lms_loan_daily | row count: 5424
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_02_01.csv
2024-03-01 | lms_loan_daily | row count: 5425
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_03_01.csv
2024-04-01 | lms_loan_daily | row count: 5417
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_04_01.csv
2024-05-01 | lms_loan_daily | row count: 5391
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_05_01.csv
2024-06-01 | lms_loan_daily | row count: 5418
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_06_01.csv
2024-07-01 | lms_loan_daily | row count: 5442
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_07_01.csv
2024-08-01 | lms_loan_daily | row count: 5531
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_08_01.csv
2024-09-01 | lms_loan_daily | row count: 5537
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_09_01.csv
2024-10-01 | lms_loan_daily | row count: 5502
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_10_01.csv
2024-11-01 | lms_loan_daily | row count: 5501
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_11_01.csv
2024-12-01 | lms_loan_daily | row count: 5531
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2024_12_01.csv
2025-01-01 | lms_loan_daily | row count: 5539
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_01_01.csv
2025-02-01 | lms_loan_daily | row count: 5028
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_02_01.csv
2025-03-01 | lms_loan_daily | row count: 4515
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_03_01.csv
2025-04-01 | lms_loan_daily | row count: 4024
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_04_01.csv
2025-05-01 | lms_loan_daily | row count: 3526
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_05_01.csv
2025-06-01 | lms_loan_daily | row count: 3021
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_06_01.csv
2025-07-01 | lms_loan_daily | row count: 2478
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_07_01.csv
2025-08-01 | lms_loan_daily | row count: 1985
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_08_01.csv
2025-09-01 | lms_loan_daily | row count: 1529
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_09_01.csv
2025-10-01 | lms_loan_daily | row count: 1041
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_10_01.csv
2025-11-01 | lms_loan_daily | row count: 526
saved to: datamart/bronze/loan/bronze_lms_loan_daily_2025_11_01.csv

=== Processing feature_clickstream ===
2023-01-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_01_01.csv
2023-02-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_02_01.csv
2023-03-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_03_01.csv
2023-04-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_04_01.csv
2023-05-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_05_01.csv
2023-06-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_06_01.csv
2023-07-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_07_01.csv
2023-08-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_08_01.csv
2023-09-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_09_01.csv
2023-10-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_10_01.csv
2023-11-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_11_01.csv
2023-12-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_12_01.csv
2024-01-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_01_01.csv
2024-02-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_02_01.csv
2024-03-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_03_01.csv
2024-04-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_04_01.csv
2024-05-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_05_01.csv
2024-06-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_06_01.csv
2024-07-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_07_01.csv
2024-08-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_08_01.csv
2024-09-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_09_01.csv
2024-10-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_10_01.csv
2024-11-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_11_01.csv
2024-12-01 | feature_clickstream | row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_12_01.csv
2025-01-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_01_01.csv
2025-02-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_02_01.csv
2025-03-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_03_01.csv
2025-04-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_04_01.csv
2025-05-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_05_01.csv
2025-06-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_06_01.csv
2025-07-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_07_01.csv
2025-08-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_08_01.csv
2025-09-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_09_01.csv
2025-10-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_10_01.csv
2025-11-01 | feature_clickstream | row count: 0
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2025_11_01.csv

=== Processing features_attributes ===
2023-01-01 | features_attributes | row count: 530
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_01_01.csv
2023-02-01 | features_attributes | row count: 501
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_02_01.csv
2023-03-01 | features_attributes | row count: 506
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_03_01.csv
2023-04-01 | features_attributes | row count: 510
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_04_01.csv
2023-05-01 | features_attributes | row count: 521
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_05_01.csv
2023-06-01 | features_attributes | row count: 517
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_06_01.csv
2023-07-01 | features_attributes | row count: 471
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_07_01.csv
2023-08-01 | features_attributes | row count: 481
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_08_01.csv
2023-09-01 | features_attributes | row count: 454
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_09_01.csv
2023-10-01 | features_attributes | row count: 487
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_10_01.csv
2023-11-01 | features_attributes | row count: 491
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_11_01.csv
2023-12-01 | features_attributes | row count: 489
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_12_01.csv
2024-01-01 | features_attributes | row count: 485
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_01_01.csv
2024-02-01 | features_attributes | row count: 518
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_02_01.csv
2024-03-01 | features_attributes | row count: 511
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_03_01.csv
2024-04-01 | features_attributes | row count: 513
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_04_01.csv
2024-05-01 | features_attributes | row count: 491
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_05_01.csv
2024-06-01 | features_attributes | row count: 498
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_06_01.csv
2024-07-01 | features_attributes | row count: 505
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_07_01.csv
2024-08-01 | features_attributes | row count: 543
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_08_01.csv
2024-09-01 | features_attributes | row count: 493
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_09_01.csv
2024-10-01 | features_attributes | row count: 456
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_10_01.csv
2024-11-01 | features_attributes | row count: 488
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_11_01.csv
2024-12-01 | features_attributes | row count: 515
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_12_01.csv
2025-01-01 | features_attributes | row count: 526
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_01_01.csv
2025-02-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_02_01.csv
2025-03-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_03_01.csv
2025-04-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_04_01.csv
2025-05-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_05_01.csv
2025-06-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_06_01.csv
2025-07-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_07_01.csv
2025-08-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_08_01.csv
2025-09-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_09_01.csv
2025-10-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_10_01.csv
2025-11-01 | features_attributes | row count: 0
saved to: datamart/bronze/attributes/bronze_features_attributes_2025_11_01.csv

=== Processing features_financials ===
2023-01-01 | features_financials | row count: 530
saved to: datamart/bronze/financials/bronze_features_financials_2023_01_01.csv
2023-02-01 | features_financials | row count: 501
saved to: datamart/bronze/financials/bronze_features_financials_2023_02_01.csv
2023-03-01 | features_financials | row count: 506
saved to: datamart/bronze/financials/bronze_features_financials_2023_03_01.csv
2023-04-01 | features_financials | row count: 510
saved to: datamart/bronze/financials/bronze_features_financials_2023_04_01.csv
2023-05-01 | features_financials | row count: 521
saved to: datamart/bronze/financials/bronze_features_financials_2023_05_01.csv
2023-06-01 | features_financials | row count: 517
saved to: datamart/bronze/financials/bronze_features_financials_2023_06_01.csv
2023-07-01 | features_financials | row count: 471
saved to: datamart/bronze/financials/bronze_features_financials_2023_07_01.csv
2023-08-01 | features_financials | row count: 481
saved to: datamart/bronze/financials/bronze_features_financials_2023_08_01.csv
2023-09-01 | features_financials | row count: 454
saved to: datamart/bronze/financials/bronze_features_financials_2023_09_01.csv
2023-10-01 | features_financials | row count: 487
saved to: datamart/bronze/financials/bronze_features_financials_2023_10_01.csv
2023-11-01 | features_financials | row count: 491
saved to: datamart/bronze/financials/bronze_features_financials_2023_11_01.csv
2023-12-01 | features_financials | row count: 489
saved to: datamart/bronze/financials/bronze_features_financials_2023_12_01.csv
2024-01-01 | features_financials | row count: 485
saved to: datamart/bronze/financials/bronze_features_financials_2024_01_01.csv
2024-02-01 | features_financials | row count: 518
saved to: datamart/bronze/financials/bronze_features_financials_2024_02_01.csv
2024-03-01 | features_financials | row count: 511
saved to: datamart/bronze/financials/bronze_features_financials_2024_03_01.csv
2024-04-01 | features_financials | row count: 513
saved to: datamart/bronze/financials/bronze_features_financials_2024_04_01.csv
2024-05-01 | features_financials | row count: 491
saved to: datamart/bronze/financials/bronze_features_financials_2024_05_01.csv
2024-06-01 | features_financials | row count: 498
saved to: datamart/bronze/financials/bronze_features_financials_2024_06_01.csv
2024-07-01 | features_financials | row count: 505
saved to: datamart/bronze/financials/bronze_features_financials_2024_07_01.csv
2024-08-01 | features_financials | row count: 543
saved to: datamart/bronze/financials/bronze_features_financials_2024_08_01.csv
2024-09-01 | features_financials | row count: 493
saved to: datamart/bronze/financials/bronze_features_financials_2024_09_01.csv
2024-10-01 | features_financials | row count: 456
saved to: datamart/bronze/financials/bronze_features_financials_2024_10_01.csv
2024-11-01 | features_financials | row count: 488
saved to: datamart/bronze/financials/bronze_features_financials_2024_11_01.csv
2024-12-01 | features_financials | row count: 515
saved to: datamart/bronze/financials/bronze_features_financials_2024_12_01.csv
2025-01-01 | features_financials | row count: 526
saved to: datamart/bronze/financials/bronze_features_financials_2025_01_01.csv
2025-02-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_02_01.csv
2025-03-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_03_01.csv
2025-04-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_04_01.csv
2025-05-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_05_01.csv
2025-06-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_06_01.csv
2025-07-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_07_01.csv
2025-08-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_08_01.csv
2025-09-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_09_01.csv
2025-10-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_10_01.csv
2025-11-01 | features_financials | row count: 0
saved to: datamart/bronze/financials/bronze_features_financials_2025_11_01.csv

In [9]:
# inspect one partition per table
for data_file_name, directory in bronze_tables:
    files = [f for f in os.listdir(directory) if f.endswith('.csv')]
    print(f"{data_file_name}: {len(files)} partitions saved")

lms_loan_daily: 35 partitions saved
feature_clickstream: 35 partitions saved
features_attributes: 35 partitions saved
features_financials: 35 partitions saved

In [10]:
# inspect bronze output, one sample partition per table
sample_date = "2023_05_01"

for data_file_name, directory in bronze_tables:
    partition_name = f"bronze_{data_file_name}_{sample_date}.csv"
    filepath = os.path.join(directory, partition_name)
    df = spark.read.csv(filepath, header=True, inferSchema=True)
    print(f"\n=== {data_file_name} | {sample_date} ===")
    print(f"Row count: {df.count()}, Columns: {len(df.columns)}")
    df.show(3)

=== lms_loan_daily | 2023_05_01 ===
Row count: 2568, Columns: 11
+--------------------+-----------+---------------+------+---------------+--------+-------+--------+-----------+-------+-------------+
|             loan_id|Customer_ID|loan_start_date|tenure|installment_num|loan_amt|due_amt|paid_amt|overdue_amt|balance|snapshot_date|
+--------------------+-----------+---------------+------+---------------+--------+-------+--------+-----------+-------+-------------+
|CUS_0x1000_2023_0...| CUS_0x1000|     2023-05-01|    10|              0|   10000|    0.0|     0.0|        0.0|10000.0|   2023-05-01|
|CUS_0x1037_2023_0...| CUS_0x1037|     2023-01-01|    10|              4|   10000| 1000.0|  1000.0|        0.0| 6000.0|   2023-05-01|
|CUS_0x1056_2023_0...| CUS_0x1056|     2023-04-01|    10|              1|   10000| 1000.0|     0.0|     1000.0|10000.0|   2023-05-01|
+--------------------+-----------+---------------+------+---------------+--------+-------+--------+-----------+-------+-------------+
only showing top 3 rows


=== feature_clickstream | 2023_05_01 ===
Row count: 8974, Columns: 22
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
|fe_1|fe_2|fe_3|fe_4|fe_5|fe_6|fe_7|fe_8|fe_9|fe_10|fe_11|fe_12|fe_13|fe_14|fe_15|fe_16|fe_17|fe_18|fe_19|fe_20|Customer_ID|snapshot_date|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
| 203|  75| 223|  88| 188| 164|  82|  18| 195|   50|  276|   50|    4|  -41|  184|  150|  212|  139|    1|   46| CUS_0x1037|   2023-05-01|
|  -4|  72| 151|  79| 170| 181|  20| 335| 320|  191|    8|  106|  249|  197|  209|  -19|  202|   61|   43|  124| CUS_0x1069|   2023-05-01|
| 150| 165|  96|  21| -45| 109| 196| 162| 188|  233|   13|  182| -177|  250|   97|  129| -152|  120|  185|  162| CUS_0x114a|   2023-05-01|
+----+----+----+----+----+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----------+-------------+
only showing top 3 rows


=== features_attributes | 2023_05_01 ===
Row count: 521, Columns: 6
+-----------+-----------------+---+-----------+----------+-------------+
|Customer_ID|             Name|Age|        SSN|Occupation|snapshot_date|
+-----------+-----------------+---+-----------+----------+-------------+
| CUS_0x1000|   Alistair Barrf| 18|913-74-1218|    Lawyer|   2023-05-01|
| CUS_0x108a|          Silvial| 38|394-00-8142|Journalist|   2023-05-01|
| CUS_0x10f9|Gilles Guillaumev| 54|746-79-6875|   _______|   2023-05-01|
+-----------+-----------------+---+-----------+----------+-------------+
only showing top 3 rows


=== features_financials | 2023_05_01 ===
Row count: 521, Columns: 22
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+--------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+--------------------+---------------------+-------------------+-----------------------+--------------------+------------------+-------------+
|Customer_ID|Annual_Income|Monthly_Inhand_Salary|Num_Bank_Accounts|Num_Credit_Card|Interest_Rate|Num_of_Loan|        Type_of_Loan|Delay_from_due_date|Num_of_Delayed_Payment|Changed_Credit_Limit|Num_Credit_Inquiries|Credit_Mix|Outstanding_Debt|Credit_Utilization_Ratio|  Credit_History_Age|Payment_of_Min_Amount|Total_EMI_per_month|Amount_invested_monthly|   Payment_Behaviour|   Monthly_Balance|snapshot_date|
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+--------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+--------------------+---------------------+-------------------+-----------------------+--------------------+------------------+-------------+
| CUS_0x1000|     30625.94|   2706.1616666666664|                6|              5|           27|          2|Credit-Builder Lo...|                 57|                    26|                1.63|                11.0|       Bad|         1562.91|       30.07719135017377|10 Years and 9 Mo...|                  Yes| 42.941090422469365|      77.31427572208112|High_spent_Medium...|400.36080052211616|   2023-05-01|
| CUS_0x108a|     36982.36|    2554.813823273585|                7|              9|           21|          9|Student Loan, Stu...|                 15|                    15|               24.61|                15.0|         _|         4882.12|      32.002993587280805|7 Years and 9 Months|                  Yes| 454.41955211428353|      275.8074536448028|Low_spent_Medium_...| 84.70883763399478|   2023-05-01|
| CUS_0x10f9|    150131.68|   11102.135321735655|                5|              1|            4|          0|                NULL|                  8|                     0|                7.49|                 0.0|      Good|         1138.36|        45.2558066955709|31 Years and 11 M...|                   No| 1494.8380115976777|      180.7591380504137|High_spent_Medium...|  1328.93819528292|   2023-05-01|
+-----------+-------------+---------------------+-----------------+---------------+-------------+-----------+--------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+--------------------+---------------------+-------------------+-----------------------+--------------------+------------------+-------------+
only showing top 3 rows

## Build Silver Table

In [11]:
# create folder for silver
silver_loan_directory = "datamart/silver/loan/"
if not os.path.exists(silver_loan_directory):
    os.makedirs(silver_loan_directory)

In [12]:
# Run Silver backfill for separated files. Here is Silver loan table.

for date_str in dates_str_lst:
    utils.data_processing_silver_loan.process_silver_loan(
        date_str, bronze_loan_directory, silver_loan_directory, spark
    )

loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_01_01.csv row count: 530
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_01_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_02_01.csv row count: 1031
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_02_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_03_01.csv row count: 1537
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_03_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_04_01.csv row count: 2047
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_04_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_05_01.csv row count: 2568
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_05_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_06_01.csv row count: 3085
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_06_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_07_01.csv row count: 3556
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_07_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_08_01.csv row count: 4037
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_08_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_09_01.csv row count: 4491
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_09_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_10_01.csv row count: 4978
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_10_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_11_01.csv row count: 5469
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_11_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_12_01.csv row count: 5428
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_12_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_01_01.csv row count: 5412
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_01_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_02_01.csv row count: 5424
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_02_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_03_01.csv row count: 5425
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_03_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_04_01.csv row count: 5417
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_04_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_05_01.csv row count: 5391
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_05_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_06_01.csv row count: 5418
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_06_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_07_01.csv row count: 5442
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_07_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_08_01.csv row count: 5531
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_08_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_09_01.csv row count: 5537
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_09_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_10_01.csv row count: 5502
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_10_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_11_01.csv row count: 5501
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_11_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2024_12_01.csv row count: 5531
saved to: datamart/silver/loan/silver_lms_loan_daily_2024_12_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_01_01.csv row count: 5539
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_01_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_02_01.csv row count: 5028
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_02_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_03_01.csv row count: 4515
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_03_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_04_01.csv row count: 4024
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_04_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_05_01.csv row count: 3526
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_05_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_06_01.csv row count: 3021
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_06_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_07_01.csv row count: 2478
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_07_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_08_01.csv row count: 1985
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_08_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_09_01.csv row count: 1529
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_09_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_10_01.csv row count: 1041
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_10_01.parquet
loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2025_11_01.csv row count: 526
saved to: datamart/silver/loan/silver_lms_loan_daily_2025_11_01.parquet

In [13]:
# Check Silver loan
date_str = "2023-05-01"
utils.data_processing_silver_loan.process_silver_loan(date_str, bronze_loan_directory, silver_loan_directory, spark).toPandas()

loaded from: datamart/bronze/loan/bronze_lms_loan_daily_2023_05_01.csv row count: 2568
saved to: datamart/silver/loan/silver_lms_loan_daily_2023_05_01.parquet

,loan_id,Customer_ID,loan_start_date,tenure,installment_num,loan_amt,due_amt,paid_amt,overdue_amt,balance,snapshot_date,mob,installments_missed,first_missed_date,dpd
0,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,0,10000.0,0.0,0.0,0.0,10000.0,2023-05-01,0,0,None,0
1,CUS_0x1037_2023_01_01,CUS_0x1037,2023-01-01,10,4,10000.0,1000.0,1000.0,0.0,6000.0,2023-05-01,4,0,None,0
2,CUS_0x1056_2023_04_01,CUS_0x1056,2023-04-01,10,1,10000.0,1000.0,0.0,1000.0,10000.0,2023-05-01,1,1,2023-04-01,30
3,CUS_0x1069_2023_01_01,CUS_0x1069,2023-01-01,10,4,10000.0,1000.0,1000.0,0.0,6000.0,2023-05-01,4,0,None,0
4,CUS_0x108a_2023_05_01,CUS_0x108a,2023-05-01,10,0,10000.0,0.0,0.0,0.0,10000.0,2023-05-01,0,0,None,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2563,CUS_0xfaf_2023_04_01,CUS_0xfaf,2023-04-01,10,1,10000.0,1000.0,1000.0,0.0,9000.0,2023-05-01,1,0,None,0
2564,CUS_0xfb6_2023_04_01,CUS_0xfb6,2023-04-01,10,1,10000.0,1000.0,1000.0,0.0,9000.0,2023-05-01,1,0,None,0
2565,CUS_0xfc9_2023_01_01,CUS_0xfc9,2023-01-01,10,4,10000.0,1000.0,0.0,3000.0,9000.0,2023-05-01,4,3,2023-02-01,89
2566,CUS_0xfcb_2023_04_01,CUS_0xfcb,2023-04-01,10,1,10000.0,1000.0,1000.0,0.0,9000.0,2023-05-01,1,0,None,0
2567,CUS_0xfcc_2023_02_01,CUS_0xfcc,2023-02-01,10,3,10000.0,1000.0,1000.0,0.0,7000.0,2023-05-01,3,0,None,0

In [14]:
silver_attributes_directory = "datamart/silver/attributes/"
if not os.path.exists(silver_attributes_directory):
    os.makedirs(silver_attributes_directory)

In [15]:
# Silver backfill for attributes table.
for date_str in dates_str_lst:
    utils.data_processing_silver_attributes.process_silver_attributes(
        date_str, bronze_attributes_directory, silver_attributes_directory, spark
    )

loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_01_01.csv | row count: 530
saved to: datamart/silver/attributes/silver_features_attributes_2023_01_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_02_01.csv | row count: 501
saved to: datamart/silver/attributes/silver_features_attributes_2023_02_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_03_01.csv | row count: 506
saved to: datamart/silver/attributes/silver_features_attributes_2023_03_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_04_01.csv | row count: 510
saved to: datamart/silver/attributes/silver_features_attributes_2023_04_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_05_01.csv | row count: 521
saved to: datamart/silver/attributes/silver_features_attributes_2023_05_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_06_01.csv | row count: 517
saved to: datamart/silver/attributes/silver_features_attributes_2023_06_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_07_01.csv | row count: 471
saved to: datamart/silver/attributes/silver_features_attributes_2023_07_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_08_01.csv | row count: 481
saved to: datamart/silver/attributes/silver_features_attributes_2023_08_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_09_01.csv | row count: 454
saved to: datamart/silver/attributes/silver_features_attributes_2023_09_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_10_01.csv | row count: 487
saved to: datamart/silver/attributes/silver_features_attributes_2023_10_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_11_01.csv | row count: 491
saved to: datamart/silver/attributes/silver_features_attributes_2023_11_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_12_01.csv | row count: 489
saved to: datamart/silver/attributes/silver_features_attributes_2023_12_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_01_01.csv | row count: 485
saved to: datamart/silver/attributes/silver_features_attributes_2024_01_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_02_01.csv | row count: 518
saved to: datamart/silver/attributes/silver_features_attributes_2024_02_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_03_01.csv | row count: 511
saved to: datamart/silver/attributes/silver_features_attributes_2024_03_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_04_01.csv | row count: 513
saved to: datamart/silver/attributes/silver_features_attributes_2024_04_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_05_01.csv | row count: 491
saved to: datamart/silver/attributes/silver_features_attributes_2024_05_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_06_01.csv | row count: 498
saved to: datamart/silver/attributes/silver_features_attributes_2024_06_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_07_01.csv | row count: 505
saved to: datamart/silver/attributes/silver_features_attributes_2024_07_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_08_01.csv | row count: 543
saved to: datamart/silver/attributes/silver_features_attributes_2024_08_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_09_01.csv | row count: 493
saved to: datamart/silver/attributes/silver_features_attributes_2024_09_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_10_01.csv | row count: 456
saved to: datamart/silver/attributes/silver_features_attributes_2024_10_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_11_01.csv | row count: 488
saved to: datamart/silver/attributes/silver_features_attributes_2024_11_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2024_12_01.csv | row count: 515
saved to: datamart/silver/attributes/silver_features_attributes_2024_12_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_01_01.csv | row count: 526
saved to: datamart/silver/attributes/silver_features_attributes_2025_01_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_02_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_02_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_03_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_03_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_04_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_04_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_05_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_05_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_06_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_06_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_07_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_07_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_08_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_08_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_09_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_09_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_10_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_10_01.parquet
loaded from: datamart/bronze/attributes/bronze_features_attributes_2025_11_01.csv | row count: 0
saved to: datamart/silver/attributes/silver_features_attributes_2025_11_01.parquet

In [16]:
# Check Silver attributes
date_str = "2023-05-01"
utils.data_processing_silver_attributes.process_silver_attributes(date_str, bronze_attributes_directory, silver_attributes_directory, spark).toPandas()

loaded from: datamart/bronze/attributes/bronze_features_attributes_2023_05_01.csv | row count: 521
saved to: datamart/silver/attributes/silver_features_attributes_2023_05_01.parquet

    Customer_ID   Age     Occupation snapshot_date
0    CUS_0x1000  18.0         Lawyer    2023-05-01
1    CUS_0x108a  38.0     Journalist    2023-05-01
2    CUS_0x10f9  54.0           None    2023-05-01
3    CUS_0x1119  36.0   Entrepreneur    2023-05-01
4    CUS_0x1192   NaN  Media_Manager    2023-05-01
..          ...   ...            ...           ...
516   CUS_0xe2f  30.0      Developer    2023-05-01
517   CUS_0xe36  29.0       Mechanic    2023-05-01
518   CUS_0xf01  35.0      Developer    2023-05-01
519   CUS_0xf45  28.0       Mechanic    2023-05-01
520   CUS_0xf9f   NaN        Manager    2023-05-01

[521 rows x 4 columns]

In [17]:
silver_financials_directory = "datamart/silver/financials/"
if not os.path.exists(silver_financials_directory):
    os.makedirs(silver_financials_directory)

In [18]:
# Run Silver backfill for financials table

for date_str in dates_str_lst:
    utils.data_processing_silver_financials.process_silver_financials(
        date_str, bronze_financials_directory, silver_financials_directory, spark
    )

loaded from: datamart/bronze/financials/bronze_features_financials_2023_01_01.csv | row count: 530
saved to: datamart/silver/financials/silver_features_financials_2023_01_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_02_01.csv | row count: 501
saved to: datamart/silver/financials/silver_features_financials_2023_02_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_03_01.csv | row count: 506
saved to: datamart/silver/financials/silver_features_financials_2023_03_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_04_01.csv | row count: 510
saved to: datamart/silver/financials/silver_features_financials_2023_04_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_05_01.csv | row count: 521
saved to: datamart/silver/financials/silver_features_financials_2023_05_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_06_01.csv | row count: 517
saved to: datamart/silver/financials/silver_features_financials_2023_06_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_07_01.csv | row count: 471
saved to: datamart/silver/financials/silver_features_financials_2023_07_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_08_01.csv | row count: 481
saved to: datamart/silver/financials/silver_features_financials_2023_08_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_09_01.csv | row count: 454
saved to: datamart/silver/financials/silver_features_financials_2023_09_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_10_01.csv | row count: 487
saved to: datamart/silver/financials/silver_features_financials_2023_10_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_11_01.csv | row count: 491
saved to: datamart/silver/financials/silver_features_financials_2023_11_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2023_12_01.csv | row count: 489
saved to: datamart/silver/financials/silver_features_financials_2023_12_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_01_01.csv | row count: 485
saved to: datamart/silver/financials/silver_features_financials_2024_01_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_02_01.csv | row count: 518
saved to: datamart/silver/financials/silver_features_financials_2024_02_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_03_01.csv | row count: 511
saved to: datamart/silver/financials/silver_features_financials_2024_03_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_04_01.csv | row count: 513
saved to: datamart/silver/financials/silver_features_financials_2024_04_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_05_01.csv | row count: 491
saved to: datamart/silver/financials/silver_features_financials_2024_05_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_06_01.csv | row count: 498
saved to: datamart/silver/financials/silver_features_financials_2024_06_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_07_01.csv | row count: 505
saved to: datamart/silver/financials/silver_features_financials_2024_07_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_08_01.csv | row count: 543
saved to: datamart/silver/financials/silver_features_financials_2024_08_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_09_01.csv | row count: 493
saved to: datamart/silver/financials/silver_features_financials_2024_09_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_10_01.csv | row count: 456
saved to: datamart/silver/financials/silver_features_financials_2024_10_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_11_01.csv | row count: 488
saved to: datamart/silver/financials/silver_features_financials_2024_11_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2024_12_01.csv | row count: 515
saved to: datamart/silver/financials/silver_features_financials_2024_12_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_01_01.csv | row count: 526
saved to: datamart/silver/financials/silver_features_financials_2025_01_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_02_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_02_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_03_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_03_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_04_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_04_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_05_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_05_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_06_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_06_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_07_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_07_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_08_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_08_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_09_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_09_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_10_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_10_01.parquet
loaded from: datamart/bronze/financials/bronze_features_financials_2025_11_01.csv | row count: 0
saved to: datamart/silver/financials/silver_features_financials_2025_11_01.parquet

In [19]:
# Check Silver fianancials
date_str = "2023-05-01"
utils.data_processing_silver_financials.process_silver_financials(date_str, bronze_financials_directory, silver_financials_directory, spark).toPandas()

loaded from: datamart/bronze/financials/bronze_features_financials_2023_05_01.csv | row count: 521
saved to: datamart/silver/financials/silver_features_financials_2023_05_01.parquet

,Customer_ID,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,...,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,snapshot_date,spending_level,payment_value_level
0,CUS_0x1000,30625.939453,2706.161621,6.0,5.0,27.0,2.0,57,26.0,1.630000,...,1562.910034,30.077190,129,Yes,42.941090,77.314278,400.360809,2023-05-01,1.0,1.0
1,CUS_0x108a,36982.359375,2554.813721,7.0,9.0,21.0,9.0,15,15.0,24.610001,...,4882.120117,32.002995,93,Yes,454.419556,275.807465,84.708839,2023-05-01,0.0,1.0
2,CUS_0x10f9,150131.687500,11102.135742,5.0,1.0,4.0,0.0,8,0.0,7.490000,...,1138.359985,45.255806,383,No,NaN,180.759140,1328.938232,2023-05-01,1.0,1.0
3,CUS_0x1119,56301.898438,4593.825195,9.0,5.0,26.0,2.0,15,18.0,14.730000,...,2161.229980,37.381496,174,Yes,50.119347,310.844452,378.418701,2023-05-01,0.0,1.0
4,CUS_0x1192,16319.375000,1518.947876,7.0,3.0,1.0,2.0,16,13.0,7.670000,...,1275.319946,31.404446,285,None,16.291128,112.339867,303.263794,2023-05-01,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,CUS_0xe2f,64404.160156,4861.145020,6.0,8.0,21.0,6.0,42,19.0,9.050000,...,2075.580078,32.071163,244,Yes,NaN,482.333160,136.916595,2023-05-01,0.0,1.0
517,CUS_0xe36,46264.710938,3857.392578,8.0,9.0,27.0,NaN,51,12.0,3.340000,...,3025.100098,31.956572,150,Yes,249.029404,127.588844,269.121002,2023-05-01,1.0,0.0
518,CUS_0xf01,30256.849609,2226.404053,0.0,5.0,5.0,3.0,21,2.0,0.730000,...,1483.229980,28.165590,245,No,62.105156,157.190964,273.344299,2023-05-01,0.0,2.0
519,CUS_0xf45,32057.300781,2606.441650,9.0,8.0,16.0,7.0,45,25.0,1.400000,...,1327.260010,38.598793,124,Yes,164.859421,207.577087,178.207657,2023-05-01,0.0,0.0
520,CUS_0xf9f,18587.640625,1578.969971,6.0,8.0,17.0,7.0,35,26.0,12.100000,...,2370.010010,26.055609,100,Yes,61.099331,93.920883,292.876801,2023-05-01,0.0,0.0

In [20]:
silver_clickstream_directory = "datamart/silver/clickstream/"
if not os.path.exists(silver_clickstream_directory):
    os.makedirs(silver_clickstream_directory)

In [21]:
# Run Silver backfill for clickstream table

for date_str in dates_str_lst:
    utils.data_processing_silver_clickstream.process_silver_clickstream(
        date_str, bronze_clickstream_directory, silver_clickstream_directory, spark
    )

loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_01_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_01_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_02_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_02_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_03_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_03_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_04_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_04_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_05_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_05_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_06_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_06_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_07_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_07_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_08_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_08_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_09_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_09_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_10_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_10_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_11_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_11_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_12_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_12_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_01_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_01_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_02_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_02_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_03_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_03_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_04_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_04_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_05_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_05_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_06_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_06_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_07_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_07_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_08_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_08_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_09_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_09_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_10_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_10_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_11_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_11_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2024_12_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2024_12_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_01_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_01_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_02_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_02_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_03_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_03_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_04_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_04_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_05_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_05_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_06_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_06_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_07_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_07_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_08_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_08_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_09_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_09_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_10_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_10_01.parquet
loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2025_11_01.csv | row count: 0
saved to: datamart/silver/clickstream/silver_feature_clickstream_2025_11_01.parquet

In [22]:
# Check Silver clickstream
date_str = "2023-05-01"
utils.data_processing_silver_clickstream.process_silver_clickstream(date_str, bronze_clickstream_directory, silver_clickstream_directory, spark).toPandas()

loaded from: datamart/bronze/clickstream/bronze_feature_clickstream_2023_05_01.csv | row count: 8974
saved to: datamart/silver/clickstream/silver_feature_clickstream_2023_05_01.parquet

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,...,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20,Customer_ID,snapshot_date
0,203,75,223,88,188,164,82,18,195,50,...,4,-41,184,150,212,139,1,46,CUS_0x1037,2023-05-01
1,-4,72,151,79,170,181,20,335,320,191,...,249,197,209,-19,202,61,43,124,CUS_0x1069,2023-05-01
2,150,165,96,21,-45,109,196,162,188,233,...,-177,250,97,129,-152,120,185,162,CUS_0x114a,2023-05-01
3,-19,269,78,70,126,-93,195,-31,99,131,...,122,123,362,60,84,36,70,220,CUS_0x1184,2023-05-01
4,46,69,19,-30,-44,-41,194,94,45,-37,...,362,28,100,108,91,-217,78,73,CUS_0x1297,2023-05-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8969,65,133,210,97,181,191,-116,185,141,100,...,43,103,235,138,78,200,145,153,CUS_0xdf6,2023-05-01
8970,149,-28,150,93,165,-48,-46,244,123,49,...,261,146,307,68,-49,77,248,107,CUS_0xe23,2023-05-01
8971,136,218,-65,-105,-156,124,71,77,130,-1,...,340,204,126,238,73,1,192,-40,CUS_0xe4e,2023-05-01
8972,85,395,67,41,41,103,128,47,152,108,...,58,155,101,15,-140,90,41,190,CUS_0xedd,2023-05-01
8973,-29,40,259,99,137,-2,-41,46,246,109,...,316,268,219,66,-52,211,170,170,CUS_0xfe4,2023-05-01

## Build Gold table for labels/features

In [23]:
# create gold layer
gold_label_store_directory = "datamart/gold/label_store/"
gold_feature_store_directory = "datamart/gold/feature_store/"

if not os.path.exists(gold_label_store_directory):
    os.makedirs(gold_label_store_directory)

if not os.path.exists(gold_feature_store_directory):
    os.makedirs(gold_feature_store_directory)

In [24]:
# Run gold LABEL store backfill
for date_str in dates_str_lst:
    utils.data_processing_gold_table.process_labels_gold_table(
        date_str, 
        silver_loan_directory, 
        gold_label_store_directory, 
        spark, 
        dpd=30, 
        mob=6
    )

loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_01_01.parquet row count: 530
saved to: datamart/gold/label_store/gold_label_store_2023_01_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_02_01.parquet row count: 1031
saved to: datamart/gold/label_store/gold_label_store_2023_02_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_03_01.parquet row count: 1537
saved to: datamart/gold/label_store/gold_label_store_2023_03_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_04_01.parquet row count: 2047
saved to: datamart/gold/label_store/gold_label_store_2023_04_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_05_01.parquet row count: 2568
saved to: datamart/gold/label_store/gold_label_store_2023_05_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_06_01.parquet row count: 3085
saved to: datamart/gold/label_store/gold_label_store_2023_06_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_07_01.parquet row count: 3556
saved to: datamart/gold/label_store/gold_label_store_2023_07_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_08_01.parquet row count: 4037
saved to: datamart/gold/label_store/gold_label_store_2023_08_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_09_01.parquet row count: 4491
saved to: datamart/gold/label_store/gold_label_store_2023_09_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_10_01.parquet row count: 4978
saved to: datamart/gold/label_store/gold_label_store_2023_10_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_11_01.parquet row count: 5469
saved to: datamart/gold/label_store/gold_label_store_2023_11_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2023_12_01.parquet row count: 5428
saved to: datamart/gold/label_store/gold_label_store_2023_12_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_01_01.parquet row count: 5412
saved to: datamart/gold/label_store/gold_label_store_2024_01_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_02_01.parquet row count: 5424
saved to: datamart/gold/label_store/gold_label_store_2024_02_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_03_01.parquet row count: 5425
saved to: datamart/gold/label_store/gold_label_store_2024_03_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_04_01.parquet row count: 5417
saved to: datamart/gold/label_store/gold_label_store_2024_04_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_05_01.parquet row count: 5391
saved to: datamart/gold/label_store/gold_label_store_2024_05_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_06_01.parquet row count: 5418
saved to: datamart/gold/label_store/gold_label_store_2024_06_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_07_01.parquet row count: 5442
saved to: datamart/gold/label_store/gold_label_store_2024_07_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_08_01.parquet row count: 5531
saved to: datamart/gold/label_store/gold_label_store_2024_08_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_09_01.parquet row count: 5537
saved to: datamart/gold/label_store/gold_label_store_2024_09_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_10_01.parquet row count: 5502
saved to: datamart/gold/label_store/gold_label_store_2024_10_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_11_01.parquet row count: 5501
saved to: datamart/gold/label_store/gold_label_store_2024_11_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_12_01.parquet row count: 5531
saved to: datamart/gold/label_store/gold_label_store_2024_12_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_01_01.parquet row count: 5539
saved to: datamart/gold/label_store/gold_label_store_2025_01_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_02_01.parquet row count: 5028
saved to: datamart/gold/label_store/gold_label_store_2025_02_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_03_01.parquet row count: 4515
saved to: datamart/gold/label_store/gold_label_store_2025_03_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_04_01.parquet row count: 4024
saved to: datamart/gold/label_store/gold_label_store_2025_04_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_05_01.parquet row count: 3526
saved to: datamart/gold/label_store/gold_label_store_2025_05_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_06_01.parquet row count: 3021
saved to: datamart/gold/label_store/gold_label_store_2025_06_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_07_01.parquet row count: 2478
saved to: datamart/gold/label_store/gold_label_store_2025_07_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_08_01.parquet row count: 1985
saved to: datamart/gold/label_store/gold_label_store_2025_08_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_09_01.parquet row count: 1529
saved to: datamart/gold/label_store/gold_label_store_2025_09_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_10_01.parquet row count: 1041
saved to: datamart/gold/label_store/gold_label_store_2025_10_01.parquet
loaded from: datamart/silver/loan/silver_lms_loan_daily_2025_11_01.parquet row count: 526
saved to: datamart/gold/label_store/gold_label_store_2025_11_01.parquet

In [25]:
# Run gold FEATURE store backfill
for date_str in dates_str_lst:
    utils.data_processing_gold_table.process_gold_feature_store(
        date_str,
        silver_loan_directory,
        silver_attributes_directory,
        silver_financials_directory,
        silver_clickstream_directory,
        gold_feature_store_directory,
        spark,
    )

2023-01-01 | new loans: 530
saved to: datamart/gold/feature_store/gold_feature_store_2023_01_01.parquet | features: 530 rows x 106 cols
2023-02-01 | new loans: 501
saved to: datamart/gold/feature_store/gold_feature_store_2023_02_01.parquet | features: 501 rows x 106 cols
2023-03-01 | new loans: 506
saved to: datamart/gold/feature_store/gold_feature_store_2023_03_01.parquet | features: 506 rows x 106 cols
2023-04-01 | new loans: 510
saved to: datamart/gold/feature_store/gold_feature_store_2023_04_01.parquet | features: 510 rows x 106 cols
2023-05-01 | new loans: 521
saved to: datamart/gold/feature_store/gold_feature_store_2023_05_01.parquet | features: 521 rows x 106 cols
2023-06-01 | new loans: 517
saved to: datamart/gold/feature_store/gold_feature_store_2023_06_01.parquet | features: 517 rows x 106 cols
2023-07-01 | new loans: 471
saved to: datamart/gold/feature_store/gold_feature_store_2023_07_01.parquet | features: 471 rows x 106 cols
2023-08-01 | new loans: 481
saved to: datamart/gold/feature_store/gold_feature_store_2023_08_01.parquet | features: 481 rows x 106 cols
2023-09-01 | new loans: 454
saved to: datamart/gold/feature_store/gold_feature_store_2023_09_01.parquet | features: 454 rows x 106 cols
2023-10-01 | new loans: 487
saved to: datamart/gold/feature_store/gold_feature_store_2023_10_01.parquet | features: 487 rows x 106 cols
2023-11-01 | new loans: 491
saved to: datamart/gold/feature_store/gold_feature_store_2023_11_01.parquet | features: 491 rows x 106 cols
2023-12-01 | new loans: 489
saved to: datamart/gold/feature_store/gold_feature_store_2023_12_01.parquet | features: 489 rows x 106 cols
2024-01-01 | new loans: 485
saved to: datamart/gold/feature_store/gold_feature_store_2024_01_01.parquet | features: 485 rows x 106 cols
2024-02-01 | new loans: 518
saved to: datamart/gold/feature_store/gold_feature_store_2024_02_01.parquet | features: 518 rows x 106 cols
2024-03-01 | new loans: 511
saved to: datamart/gold/feature_store/gold_feature_store_2024_03_01.parquet | features: 511 rows x 106 cols
2024-04-01 | new loans: 513
saved to: datamart/gold/feature_store/gold_feature_store_2024_04_01.parquet | features: 513 rows x 106 cols
2024-05-01 | new loans: 491
saved to: datamart/gold/feature_store/gold_feature_store_2024_05_01.parquet | features: 491 rows x 106 cols
2024-06-01 | new loans: 498
saved to: datamart/gold/feature_store/gold_feature_store_2024_06_01.parquet | features: 498 rows x 106 cols
2024-07-01 | new loans: 505
saved to: datamart/gold/feature_store/gold_feature_store_2024_07_01.parquet | features: 505 rows x 106 cols
2024-08-01 | new loans: 543
saved to: datamart/gold/feature_store/gold_feature_store_2024_08_01.parquet | features: 543 rows x 106 cols
2024-09-01 | new loans: 493
saved to: datamart/gold/feature_store/gold_feature_store_2024_09_01.parquet | features: 493 rows x 106 cols
2024-10-01 | new loans: 456
saved to: datamart/gold/feature_store/gold_feature_store_2024_10_01.parquet | features: 456 rows x 106 cols
2024-11-01 | new loans: 488
saved to: datamart/gold/feature_store/gold_feature_store_2024_11_01.parquet | features: 488 rows x 106 cols
2024-12-01 | new loans: 515
saved to: datamart/gold/feature_store/gold_feature_store_2024_12_01.parquet | features: 515 rows x 106 cols
2025-01-01 | new loans: 526
saved to: datamart/gold/feature_store/gold_feature_store_2025_01_01.parquet | features: 526 rows x 106 cols
2025-02-01 | new loans: 0

Py4JJavaError: An error occurred while calling o46520.parquet.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 11 in stage 2505.0 failed 1 times, most recent failure: Lost task 11.0 in stage 2505.0 (TID 3429) (DESKTOP-QGJJJLI executor driver): org.apache.spark.SparkException: Python worker exited unexpectedly (crashed)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(PythonRunner.scala:612)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(PythonRunner.scala:594)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:789)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:766)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:525)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:385)
	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:386)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:774)
	... 25 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeWrite$4(FileFormatWriter.scala:307)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.writeAndCommit(FileFormatWriter.scala:271)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeWrite(FileFormatWriter.scala:304)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:190)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:190)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:243)
	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:802)
	at jdk.internal.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.SparkException: Python worker exited unexpectedly (crashed)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(PythonRunner.scala:612)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$1.applyOrElse(PythonRunner.scala:594)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:789)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:766)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:525)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:385)
	at org.apache.spark.sql.execution.datasources.WriteFilesExec.$anonfun$doExecuteWrite$1(WriteFiles.scala:100)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:386)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:774)
	... 25 more

In [ ]:
# Test gold feature store - single partition
date_str = "2023-05-01"
df_test = utils.data_processing_gold_table.process_gold_feature_store(
    date_str,
    silver_loan_directory,
    silver_attributes_directory,
    silver_financials_directory,
    silver_clickstream_directory,
    gold_feature_store_directory,
    spark,
)
df_test.toPandas()

2023-05-01 | new loans: 521
saved to: datamart/gold/feature_store/gold_feature_store_2023_05_01.parquet | features: 521 rows x 106 cols

,Customer_ID,loan_id,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,...,fe_19_mean,fe_19_std,fe_19_min,fe_19_max,fe_20_mean,fe_20_std,fe_20_min,fe_20_max,has_clickstream,snapshot_date
0,CUS_0x1000,CUS_0x1000_2023_05_01,18.0,7.0,30625.939453,2706.161621,6.0,5.0,27.0,2.0,...,80.8,83.902920,4,200,111.2,80.334924,31,234,1,2023-05-01
1,CUS_0x108a,CUS_0x108a_2023_05_01,38.0,6.0,36982.359375,2554.813721,7.0,9.0,21.0,9.0,...,61.2,70.563447,17,184,177.4,190.700813,-88,416,1,2023-05-01
2,CUS_0x10f9,CUS_0x10f9_2023_05_01,54.0,NaN,150131.687500,11102.135742,5.0,1.0,4.0,0.0,...,104.0,82.240501,-7,221,52.0,84.080319,-45,147,1,2023-05-01
3,CUS_0x1119,CUS_0x1119_2023_05_01,36.0,5.0,56301.898438,4593.825195,9.0,5.0,26.0,2.0,...,43.0,77.961529,-64,125,86.2,50.251368,24,161,1,2023-05-01
4,CUS_0x1192,CUS_0x1192_2023_05_01,NaN,10.0,16319.375000,1518.947876,7.0,3.0,1.0,2.0,...,144.8,104.506938,-16,246,75.4,82.832964,9,211,1,2023-05-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,CUS_0xe2f,CUS_0xe2f_2023_05_01,30.0,2.0,64404.160156,4861.145020,6.0,8.0,21.0,6.0,...,94.4,139.528850,-60,276,43.8,72.675305,-59,108,1,2023-05-01
517,CUS_0xe36,CUS_0xe36_2023_05_01,29.0,9.0,46264.710938,3857.392578,8.0,9.0,27.0,NaN,...,126.4,75.118573,5,197,35.6,54.270618,-21,114,1,2023-05-01
518,CUS_0xf01,CUS_0xf01_2023_05_01,35.0,2.0,30256.849609,2226.404053,0.0,5.0,5.0,3.0,...,64.0,103.348924,-45,208,96.6,78.446160,-9,192,1,2023-05-01
519,CUS_0xf45,CUS_0xf45_2023_05_01,28.0,9.0,32057.300781,2606.441650,9.0,8.0,16.0,7.0,...,110.4,89.410849,-26,175,58.0,43.531598,-15,98,1,2023-05-01
520,CUS_0xf9f,CUS_0xf9f_2023_05_01,NaN,8.0,18587.640625,1578.969971,6.0,8.0,17.0,7.0,...,125.2,102.711733,15,258,56.0,118.399747,-109,186,1,2023-05-01

In [ ]:
df_test.printSchema()

root
 |-- Customer_ID: string (nullable = true)
 |-- loan_id: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- Occupation: integer (nullable = true)
 |-- Annual_Income: float (nullable = true)
 |-- Monthly_Inhand_Salary: float (nullable = true)
 |-- Num_Bank_Accounts: integer (nullable = true)
 |-- Num_Credit_Card: integer (nullable = true)
 |-- Interest_Rate: integer (nullable = true)
 |-- Num_of_Loan: integer (nullable = true)
 |-- Delay_from_due_date: integer (nullable = true)
 |-- Num_of_Delayed_Payment: integer (nullable = true)
 |-- Changed_Credit_Limit: float (nullable = true)
 |-- Num_Credit_Inquiries: integer (nullable = true)
 |-- Credit_Mix: integer (nullable = true)
 |-- Outstanding_Debt: float (nullable = true)
 |-- Credit_Utilization_Ratio: float (nullable = true)
 |-- Credit_History_Age: integer (nullable = true)
 |-- Payment_of_Min_Amount: integer (nullable = true)
 |-- Total_EMI_per_month: float (nullable = true)
 |-- Amount_invested_monthly: float (nullable = true)
 |-- Monthly_Balance: float (nullable = true)
 |-- spending_level: integer (nullable = true)
 |-- payment_value_level: integer (nullable = true)
 |-- fe_1_mean: double (nullable = true)
 |-- fe_1_std: double (nullable = true)
 |-- fe_1_min: integer (nullable = true)
 |-- fe_1_max: integer (nullable = true)
 |-- fe_2_mean: double (nullable = true)
 |-- fe_2_std: double (nullable = true)
 |-- fe_2_min: integer (nullable = true)
 |-- fe_2_max: integer (nullable = true)
 |-- fe_3_mean: double (nullable = true)
 |-- fe_3_std: double (nullable = true)
 |-- fe_3_min: integer (nullable = true)
 |-- fe_3_max: integer (nullable = true)
 |-- fe_4_mean: double (nullable = true)
 |-- fe_4_std: double (nullable = true)
 |-- fe_4_min: integer (nullable = true)
 |-- fe_4_max: integer (nullable = true)
 |-- fe_5_mean: double (nullable = true)
 |-- fe_5_std: double (nullable = true)
 |-- fe_5_min: integer (nullable = true)
 |-- fe_5_max: integer (nullable = true)
 |-- fe_6_mean: double (nullable = true)
 |-- fe_6_std: double (nullable = true)
 |-- fe_6_min: integer (nullable = true)
 |-- fe_6_max: integer (nullable = true)
 |-- fe_7_mean: double (nullable = true)
 |-- fe_7_std: double (nullable = true)
 |-- fe_7_min: integer (nullable = true)
 |-- fe_7_max: integer (nullable = true)
 |-- fe_8_mean: double (nullable = true)
 |-- fe_8_std: double (nullable = true)
 |-- fe_8_min: integer (nullable = true)
 |-- fe_8_max: integer (nullable = true)
 |-- fe_9_mean: double (nullable = true)
 |-- fe_9_std: double (nullable = true)
 |-- fe_9_min: integer (nullable = true)
 |-- fe_9_max: integer (nullable = true)
 |-- fe_10_mean: double (nullable = true)
 |-- fe_10_std: double (nullable = true)
 |-- fe_10_min: integer (nullable = true)
 |-- fe_10_max: integer (nullable = true)
 |-- fe_11_mean: double (nullable = true)
 |-- fe_11_std: double (nullable = true)
 |-- fe_11_min: integer (nullable = true)
 |-- fe_11_max: integer (nullable = true)
 |-- fe_12_mean: double (nullable = true)
 |-- fe_12_std: double (nullable = true)
 |-- fe_12_min: integer (nullable = true)
 |-- fe_12_max: integer (nullable = true)
 |-- fe_13_mean: double (nullable = true)
 |-- fe_13_std: double (nullable = true)
 |-- fe_13_min: integer (nullable = true)
 |-- fe_13_max: integer (nullable = true)
 |-- fe_14_mean: double (nullable = true)
 |-- fe_14_std: double (nullable = true)
 |-- fe_14_min: integer (nullable = true)
 |-- fe_14_max: integer (nullable = true)
 |-- fe_15_mean: double (nullable = true)
 |-- fe_15_std: double (nullable = true)
 |-- fe_15_min: integer (nullable = true)
 |-- fe_15_max: integer (nullable = true)
 |-- fe_16_mean: double (nullable = true)
 |-- fe_16_std: double (nullable = true)
 |-- fe_16_min: integer (nullable = true)
 |-- fe_16_max: integer (nullable = true)
 |-- fe_17_mean: double (nullable = true)
 |-- fe_17_std: double (nullable = true)
 |-- fe_17_min: integer (nullable = true)
 |-- fe_17_max: integer (nullable = true)
 |-- fe_18_mean: double (nullable = true)
 |-- fe_18_std: double (nullable = true)
 |-- fe_18_min: integer (nullable = true)
 |-- fe_18_max: integer (nullable = true)
 |-- fe_19_mean: double (nullable = true)
 |-- fe_19_std: double (nullable = true)
 |-- fe_19_min: integer (nullable = true)
 |-- fe_19_max: integer (nullable = true)
 |-- fe_20_mean: double (nullable = true)
 |-- fe_20_std: double (nullable = true)
 |-- fe_20_min: integer (nullable = true)
 |-- fe_20_max: integer (nullable = true)
 |-- has_clickstream: integer (nullable = false)
 |-- snapshot_date: date (nullable = false)

In [ ]:
# Inspect full gold feature store
folder_path = gold_label_store_directory
files_list = [folder_path + os.path.basename(f) for f in glob.glob(os.path.join(folder_path, '*'))]
df_fs = spark.read.option("header", "true").parquet(*files_list)
print("row_count:", df_fs.count())
df_fs.show()

row_count: 12500
+-----------+--------------------+----+----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+------------------+---------------------+-------------------+-----------------------+---------------+--------------+-------------------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+---------------+-------------+
|Customer_ID|             loan_id| Age|Occupation|Annual_Income|Monthly_Inhand_Salary|Num_Bank_Accounts|Num_Credit_Card|Interest_Rate|Num_of_Loan|Delay_from_due_date|Num_of_Delayed_Payment|Changed_Credit_Limit|Num_Credit_Inquiries|Credit_Mix|Outstanding_Debt|Credit_Utilization_Ratio|Credit_History_Age|Payment_of_Min_Amount|Total_EMI_per_month|Amount_invested_monthly|Monthly_Balance|spending_level|payment_value_level|fe_1_mean|          fe_1_std|fe_1_min|fe_1_max|fe_2_mean|          fe_2_std|fe_2_min|fe_2_max|fe_3_mean|          fe_3_std|fe_3_min|fe_3_max|fe_4_mean|          fe_4_std|fe_4_min|fe_4_max|fe_5_mean|          fe_5_std|fe_5_min|fe_5_max|fe_6_mean|          fe_6_std|fe_6_min|fe_6_max|fe_7_mean|          fe_7_std|fe_7_min|fe_7_max|fe_8_mean|          fe_8_std|fe_8_min|fe_8_max|fe_9_mean|          fe_9_std|fe_9_min|fe_9_max|fe_10_mean|         fe_10_std|fe_10_min|fe_10_max|fe_11_mean|         fe_11_std|fe_11_min|fe_11_max|fe_12_mean|         fe_12_std|fe_12_min|fe_12_max|fe_13_mean|         fe_13_std|fe_13_min|fe_13_max|fe_14_mean|         fe_14_std|fe_14_min|fe_14_max|fe_15_mean|         fe_15_std|fe_15_min|fe_15_max|fe_16_mean|         fe_16_std|fe_16_min|fe_16_max|fe_17_mean|         fe_17_std|fe_17_min|fe_17_max|fe_18_mean|         fe_18_std|fe_18_min|fe_18_max|fe_19_mean|         fe_19_std|fe_19_min|fe_19_max|fe_20_mean|         fe_20_std|fe_20_min|fe_20_max|has_clickstream|snapshot_date|
+-----------+--------------------+----+----------+-------------+---------------------+-----------------+---------------+-------------+-----------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+------------------+---------------------+-------------------+-----------------------+---------------+--------------+-------------------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+---------+------------------+--------+--------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+----------+------------------+---------+---------+---------------+-------------+
| CUS_0x1000|CUS_0x1000_2023_0...|  18|         7|     30625.94|            2706.1616|                6|              5|           27|          2|                 57|                    26|                1.63|                  11|         0|         1562.91|                30.07719|               129|                    1|           42.94109|               77.31428|       400.3608|             1|                  1|     78.4| 95.56306818012908|     -19|     233|    122.0| 133.8487952878172|     -13|     316|    183.8|139.07983318943118|      18|     345|     12.2| 78.06855961268916|    -101|     114|    107.0|103.17945531936094|      46|     288|     91.2| 85.50263153845032|     -33|     192|    164.4| 78.86887852632368|      77|     254|    154.4| 84.09696784070161|      94|     298|    122.2|38.654883262014906|      75|     170|      56.6|133.25464344629796|     -120|      249|     134.6| 57.77802350375097|       39|      185|     135.6|164.49255302292565|      -31|      398|     113.6|129.24898452212304|      -34|      282|      99.2| 47.07653343227388|       25|      145|      86.8|114.83553457009724|      -61|      253|      62.4| 71.03027523528259|        0|      172|      43.4| 64.43446282852058|      -60|      106|      97.4| 76.47417864874392|        7|      217|      80.8| 83.90292009221133|        4|      200|     111.2| 80.33492391233092|       31|      234|              1|   2023-05-01|
| CUS_0x108a|CUS_0x108a_2023_0...|  38|         6|     36982.36|            2554.8137|                7|              9|           21|          9|                 15|                    15|               24.61|                  15|      NULL|         4882.12|               32.002995|                93|                    1|          454.41956|              275.80746|       84.70884|             0|                  1|     34.8| 47.85603410229477|     -33|      77|     99.2| 70.02642358424426|      11|     176|    104.2| 83.34086632619078|      38|     231|    140.0|162.34531098864542|     -95|     345|    142.6| 38.52661417773433|      80|     183|    119.2|122.34868205256647|      30|     328|     73.8| 63.66474691695554|      -5|     148|     94.8|179.89218993608367|    -122|     338|    133.4|103.56061027243902|       4|     268|      49.0|  197.790292987295|     -270|      272|     133.4|49.737309939320205|       67|      194|     145.4|102.04557805216255|        2|      232|     170.6| 88.23718037199512|       48|      268|      80.0| 131.0438857787726|      -50|      256|     133.0| 86.06973916540005|       12|      248|     113.0| 67.94483056127228|        4|      191|      96.2| 156.2616395664656|     -135|      297|     162.4|  185.792357216329|      -49|      429|      61.2| 70.56344662783982|       17|      184|     177.4| 190.7008127932338|      -88|      416|              1|   2023-05-01|
| CUS_0x10f9|CUS_0x10f9_2023_0...|  54|      NULL|    150131.69|            11102.136|                5|              1|            4|          0|                  8|                     0|                7.49|                   0|         2|         1138.36|               45.255806|               383|                    0|               NULL|              180.75914|      1328.9382|             1|                  1|    117.2|132.19568828066974|     -65|     269|     37.6| 66.21027110652848|     -53|     109|     68.8|  98.9226970922245|     -28|     220|    173.8|116.74202328210694|      64|     353|     84.4| 82.86615714512168|      -2|     170|     22.4|135.10292372854113|    -101|     254|     89.4| 69.28058891204664|      31|     206|     48.4| 55.88649210676942|     -15|     112|    172.4|34.202339101295394|     127|     207|     147.8|116.75915381673508|       36|      311|     133.0| 86.93388292259813|       21|      223|      50.2|101.91761378682294|      -87|      174|      64.0| 141.2002124644294|      -96|      267|      63.2|100.69607738139555|      -59|      196|     110.6| 72.95752188773959|       31|      191|      72.6| 47.44786612693978|        4|      122|      61.0| 93.11820445004295|      -48|      202|       7.8|104.71246344155982|     -119|      166|     104.0|  82.2405009712368|       -7|      221|      52.0| 84.08031874344911|      -45|      147|              1|   2023-05-01|
| CUS_0x1119|CUS_0x1119_2023_0...|  36|         5|      56301.9|             4593.825|                9|              5|           26|          2|                 15|                    18|               14.73|                  14|      NULL|         2161.23|               37.381496|               174|                    1|          50.119347|              310.84445|       378.4187|             0|                  1|     73.8|189.52757055373235|    -173|     265|    114.8|103.34747215099168|      17|     241|    145.2|117.38270741467842|      10|     279|    141.0|104.71867073258713|     -20|     262|     94.4| 70.09136894083322|       3|     195|    169.8| 77.28324527347438|      93|     284|     60.8| 77.79588678072896|     -56|     145|     72.8|124.99279979262806|     -61|     211|     72.2|143.15446203314795|     -96|     260|      75.8| 116.2742447836149|      -87|      236|      74.4| 95.84257926412457|      -83|      161|      37.8|196.69189103773445|     -200|      294|      95.0| 55.04089388809015|       37|      167|      55.0| 43.04067843331469|      -14|       89|      76.8| 72.84366822174732|        4|      167|      82.2| 87.54541678466097|      -28|      158|     152.8| 84.59728128019245|       44|      254|     156.8| 58.98474379023783|      110|      256|      43.0|  77.9615289742319|      -64|      125|      86.2| 50.25136814057902|       24|      161|              1|   2023-05-01|
| CUS_0x1192|CUS_0x1192_2023_0...|NULL|        10|    16319.375|            1518.9479|                7|              3|            1|          2|                 16|                    13|                7.67|                   9|         1|         1275.32|               31.404446|               285|                 NULL|          16.291128|              112.33987|       303.2638|             0|                  1|    160.0|121.91185340236609|     -42|     262|    179.4| 90.97417215891552|      96|     279|     71.4|  83.1763187451813|     -47|     165|    109.0| 86.54189736769122|     -43|     172|    125.6| 90.06830741165285|      24|     245|     62.4|113.64110171940432|     -37|     246|     82.6|113.07210089142237|    -107|     177|    111.6|124.58250278429952|     -72|     244|    107.0|  35.4682957019364|      73|     164|      75.2|137.08282168090938|     -151|      219|      84.8| 92.25345521984529|      -57|      180|      72.6| 75.40424391239527|       14|      190|     101.8| 50.98725330903793|       31|      157|      80.8| 66.86329336788609|      -19|      154|      64.4| 90.10160930860225|      -37|      170|     200.0|  61.6725222445134|      128|      279|     149.6|119.65283114076323|      -25|      257|      46.4|169.01272141469116|     -181|      262|     144.8|104.50693756875665|      -16|      246|      75.4| 82.83296445256562|        9|      211|              1|   2023-05-01|
| CUS_0x11b1|CUS_0x11b1_2023_0...|  28|      NULL|     34819.83|            2689.6526|             NULL|              3|           10|          1|                 14|                    12|                7.69|                   4|      NULL|          905.89|                37.69817|               226|                    1|          22.795397|              125.59961|      380.57025|             1|                  0|     66.4|118.83517997630163|     -67|     243|    150.8|  141.004255254939|      -2|     313|    203.6|  89.4108494535199|     106|     341|     54.4|130.97442498442206|    -164|     187|    146.2| 73.03903066169485|      66|     233|     26.4| 50.93427137007067|     -20|      89|    186.0| 84.51922858142991|      39|     246|    174.6| 89.13641231281412|      49|     297|    158.6| 66.93504313885217|     100|     255|      71.2| 82.73572384405664|      -55|      171|      61.8| 39.53100049328375|       13|      115|     104.4|123.54068155874809|      -16|      295|      76.0|140.09639538546307|      -64|      231|      69.0|104.08169867945085|      -36|      229|     117.0| 82.49242389456137|        6|      205|      70.6| 92.79439638254026|      -34|      220|     186.6|117.88044791228104|       42|      322|      68.2|120.19858568219512|      -85|      251|     145.4|123.76712002789756|      -59|      253|      81.0|52.364109846344185|       21|      163|              1|   2023-05-01|
| CUS_0x12a7|CUS_0x12a7_2023_0...|  37|        10|     26450.59|            2079.2158|                5|              6|           20|          4|                 24|                    18|                11.8|                   1|         1|           952.9|               26.399803|               344|                    0|           73.67019|              19.552471|       354.6989|             1|                  2|    165.4| 97.77934342180868|       8|     264|    113.6| 83.01385426541765|      -3|     219|    127.0| 81.29268109737801|       3|     188|     39.4| 87.36875871843436|     -63|     172|     47.8|  98.2710537238713|     -53|     171|     81.8|154.77952060915553|    -102|     291|    118.6|25.244801445050026|      86|     144|    114.6|124.46003374577721|      11|     319|     19.4| 100.3857559616901|     -69|     174|     174.8| 48.10093554183744|      127|      226|      66.2|53.839576521365764|      -24|      109|     106.6| 88.84987338201445|        3|      191|     169.6|108.92107234139773|       55|      324|     138.0| 59.53990258641679|       55|      221|     138.8|46.996808402273444|       62|      187|     103.2|144.47560347685004|      -53|      289|      70.8| 68.50328459278431|      -25|      159|      94.4|106.12633980308564|      -91|      174|      38.2| 85.48216188188036|      -90|      104|     120.6|146.69969325121303|      -64|      308|              1|   2023-05-01|
| CUS_0x12a9|CUS_0x12a9_2023_0...|  44|        10|     44822.21|             3555.184|                1|              4|            2|          4|                 10|                     7|                1.03|                   0|         2|          730.64|               30.058125|               289|                    0|          135.04428|              100.05342|      370.42072|             1|                  1|    122.0| 55.68662316930342|      70|     211|     67.8| 86.44478006218768|     -41|     184|     56.2| 110.3231616660799|     -48|     216|    122.2|120.34409000860823|     -45|     264|     62.8|103.51666532496108|     -73|     193|    115.4|120.89995864349994|       8|     262|     51.0| 109.3229161703986|    -119|     169|    123.6|63.645895390040664|      36|     186|    100.8| 96.37271398066986|      18|     262|     173.0| 93.71499346422641|       49|      301|     113.4| 81.39594584498666|       49|      252|      -7.8| 50.82519060465981|      -59|       75|      39.6|166.50315312329676|     -163|      287|      70.6| 47.19427931434063|       27|      127|      11.0|125.59458587057007|     -178|      157|     121.2| 52.35647046927438|       46|      190|     105.6|110.03090474952934|       -1|      245|      93.2|132.95939229704686|     -105|      221|      80.4|63.042049459071364|       22|      175|     117.0|  54.3415126767741|       64|      184|              1|   2023-05-01|
| CUS_0x1340|CUS_0x1340_2023_0...|  42|         1|     40600.61|            3420.3843|                4|              7|            6|          2|                  9|                     0|                 5.5|                   2|         2|         1198.96|                33.44434|               255|                    0|          63.614853|               75.54045|      462.88312|             1|                  0|     95.4|131.33659048414498|    -101|     215|    172.6|40.116081563383034|     119|     230|    111.0| 58.96185207403173|      43|     203|     71.0|  95.2732911156112|     -66|     174|    119.0|111.36651202224122|     -61|     217|    128.0|114.11616888066301|     -47|     236|     81.6| 36.58961601328989|      29|     129|     70.6|  73.8092135170129|     -12|     182|     99.8| 93.84934736054375|      -6|     239|     137.2|100.30553324717435|       62|      312|      70.0| 97.92854537876073|      -41|      167|      88.6| 51.51019316601327|       14|      156|      92.6|141.13752158798877|      -32|      298|      66.6| 165.7145135466414|      -98|      301|     194.6|131.43933962098257|       17|      379|      62.8|112.75060975444879|      -44|      252|      76.4| 85.88247784036042|        6|      189|     156.6| 71.94303301918818|       82|      244|      57.6|108.24647800275073|      -84|      194|     121.2|145.29865794287298|      -26|      329|              1|   2023-05-01|
| CUS_0x13d1|CUS_0x13d1_2023_0...|  22|        11|     22020.37|            1605.0309|                5|              6|            6|          3|                 19|                     6|                5.14|                   9|         2|         1343.64|               30.789167|               316|                    0|           36.59863|              208.74937|      205.15508|             0|                  0|     76.0| 98.93937537704592|     -43|     163|    121.2| 81.30006150059174|      14|     218|    143.4| 68.74809088258378|      32|     211|    146.4|154.24752834324445|    -127|     250|     91.2|  65.9787844689488|     -15|     165|    113.2| 72.27516862657603|      22|     218|    113.4| 65.78981684121031|      69|     228|    150.8| 99.89094053016021|      -1|     278|     65.0| 71.89228053136164|      -6|     165|      35.8|124.02499748034667|     -105|      216|     146.8| 88.63238685717542|       20|      242|      31.6| 49.48535136785431|      -20|      112|     138.4| 63.77538710192201|       64|      227|     126.2| 81.91275846899553|       23|      233|      94.0|101.34100848126586|       -1|      267|     161.0| 66.48308055437865|       50|      214|     140.8|104.29381573228588|      -39|      231|     101.8| 77.62538244672292|       -9|      182|     120.0| 75.46853649038121|       13|      204|      76.6| 89.91551590242922|      -55|      190|              1|   2023-05-01|
| CUS_0x13eb|CUS_0x13eb_2023_0...|  30|         6|      9335.19|             844.9325|                7|           NULL|           26|          6|                 17|                    19|               18.18|                  12|         1|          1860.2|               36.575302|               166|                    1|          41.499268|               82.41955|      250.57443|             0|                  0|     95.2| 66.34530880175328|      28|     171|    110.8| 59.35233778041098|      38|     186|     77.8|147.23009203284496|    -170|     214|    122.2|20.498780451529306|     100|     150|     81.6|118.02669189636724|     -13|     283|    133.8|114.87689062644411|      45|     332|    107.4| 65.93405796703249|      12|     186|     80.6| 61.68711372726074|      -2|     155|     84.0|49.949974974968704|      33|     144|     177.6|110.80523453339197|       19|      325|     102.0|44.232341109192944|       33|      156|     126.0|104.51315706646699|      -23|      234|     138.6|  146.250811963558|        2|      340|      58.0| 49.20365840057018|       15|      133|      53.0|109.95453605922768|     -138|      123|     123.2|121.26499907227972|      -24|      266|     103.4|110.12629113885566|        2|      253|     122.6|  92.1455370595885|      -30|      208|     101.2|    90.96262968934|       -3|      189|      91.4|  140.614010681724|      -72|      275|              1|   2023-05-01|

In [ ]:
df_label = utils.data_processing_gold_table.process_labels_gold_table(
    "2024-05-01", silver_loan_directory, gold_label_store_directory, spark, dpd=30, mob=6
)
df_label.toPandas()

loaded from: datamart/silver/loan/silver_lms_loan_daily_2024_05_01.parquet row count: 5391
saved to: datamart/gold/label_store/gold_label_store_2024_05_01.parquet

                   loan_id Customer_ID  label   label_def snapshot_date
0    CUS_0x1011_2023_11_01  CUS_0x1011      0  30dpd_6mob    2024-05-01
1    CUS_0x1018_2023_11_01  CUS_0x1018      1  30dpd_6mob    2024-05-01
2    CUS_0x1041_2023_11_01  CUS_0x1041      0  30dpd_6mob    2024-05-01
3    CUS_0x105b_2023_11_01  CUS_0x105b      0  30dpd_6mob    2024-05-01
4    CUS_0x107c_2023_11_01  CUS_0x107c      0  30dpd_6mob    2024-05-01
..                     ...         ...    ...         ...           ...
486   CUS_0xe57_2023_11_01   CUS_0xe57      1  30dpd_6mob    2024-05-01
487   CUS_0xeda_2023_11_01   CUS_0xeda      1  30dpd_6mob    2024-05-01
488   CUS_0xf19_2023_11_01   CUS_0xf19      0  30dpd_6mob    2024-05-01
489   CUS_0xf3e_2023_11_01   CUS_0xf3e      1  30dpd_6mob    2024-05-01
490   CUS_0xf50_2023_11_01   CUS_0xf50      0  30dpd_6mob    2024-05-01

[491 rows x 5 columns]

In [ ]:
folder_path = gold_label_store_directory
files_list = [folder_path + os.path.basename(f) for f in glob.glob(os.path.join(folder_path, '*'))]
df_ls = spark.read.option("header", "true").parquet(*files_list)
print("row_count:", df_ls.count())
df_ls.show()

row_count: 12500
+--------------------+-----------+-----+----------+-------------+
|             loan_id|Customer_ID|label| label_def|snapshot_date|
+--------------------+-----------+-----+----------+-------------+
|CUS_0x10ac_2024_0...| CUS_0x10ac|    0|30dpd_6mob|   2025-02-01|
|CUS_0x10c5_2024_0...| CUS_0x10c5|    1|30dpd_6mob|   2025-02-01|
|CUS_0x1145_2024_0...| CUS_0x1145|    1|30dpd_6mob|   2025-02-01|
|CUS_0x11ac_2024_0...| CUS_0x11ac|    0|30dpd_6mob|   2025-02-01|
|CUS_0x122c_2024_0...| CUS_0x122c|    0|30dpd_6mob|   2025-02-01|
|CUS_0x1274_2024_0...| CUS_0x1274|    1|30dpd_6mob|   2025-02-01|
|CUS_0x1288_2024_0...| CUS_0x1288|    1|30dpd_6mob|   2025-02-01|
|CUS_0x12cc_2024_0...| CUS_0x12cc|    1|30dpd_6mob|   2025-02-01|
|CUS_0x1338_2024_0...| CUS_0x1338|    0|30dpd_6mob|   2025-02-01|
|CUS_0x1370_2024_0...| CUS_0x1370|    1|30dpd_6mob|   2025-02-01|
|CUS_0x1378_2024_0...| CUS_0x1378|    1|30dpd_6mob|   2025-02-01|
|CUS_0x139b_2024_0...| CUS_0x139b|    0|30dpd_6mob|   2025-02-01|
|CUS_0x13a9_2024_0...| CUS_0x13a9|    0|30dpd_6mob|   2025-02-01|
|CUS_0x13ce_2024_0...| CUS_0x13ce|    0|30dpd_6mob|   2025-02-01|
|CUS_0x147a_2024_0...| CUS_0x147a|    0|30dpd_6mob|   2025-02-01|
|CUS_0x1510_2024_0...| CUS_0x1510|    1|30dpd_6mob|   2025-02-01|
|CUS_0x1572_2024_0...| CUS_0x1572|    0|30dpd_6mob|   2025-02-01|
|CUS_0x159b_2024_0...| CUS_0x159b|    0|30dpd_6mob|   2025-02-01|
|CUS_0x15f1_2024_0...| CUS_0x15f1|    0|30dpd_6mob|   2025-02-01|
|CUS_0x1621_2024_0...| CUS_0x1621|    0|30dpd_6mob|   2025-02-01|
+--------------------+-----------+-----+----------+-------------+
only showing top 20 rows

In [ ]:
df_ls.printSchema()

root
 |-- loan_id: string (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- label: integer (nullable = true)
 |-- label_def: string (nullable = true)
 |-- snapshot_date: date (nullable = true)